# Generated by Django 3.2 on 2021-04-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='author', verbose_name='Author Image', width_field=100),
        ),
    ]
